### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by YumoImer** [ant-design/x#194]
@YumoImer 
- [x] 🔥 更新 readme 
- [x] 🔥 新增对接 openai 通义 开发文档
- [x] 🔥 域名切换到 x.ant.design，host 域名配置 cname 配置
- [x] 🚗 官网设计视觉验收
- [x] 🚗 设计 Tab 设计视觉验收
- [x] 🔥 首页体验优化
- [x] 🚗 设计 Tab 设计视觉验收 - 第二波

@zombieJ 
- [x] 🔥 运营文章
- [ ] 🚗 运营文章发布渠道要梳理一下
  - [x] 语雀
  - [x] 知乎
  - [ ] HackNews
  - [x] Twitter / X
  - [x] 掘金
    - https://juejin.cn/spost/7449549889165475852
  - ❌ https://dev.to/ UI 有 bug
  - [x] https://www.reddit.com/r/reactjs/
    - https://www.reddit.com/r/reactjs/comments/1hg8pei/ant_design_x_is_out/
  - [x] https://medium.com/ant-design
    - https://medium.com/ant-design/ant-design-x-1-0-is-out-3ff7ac401dd7
  - [x] Producthunt
    - https://www.producthunt.com/posts/ant-design-x/
  - [x] https://www.echojs.com/
    - https://www.echojs.com/news/42710
  - ❌ v2ex 不能注册
  - ❌ https://frontendfront.com/ 不能注册
- [x] 🔥 DNS CNAME alias
- [x] 🚗 国内镜像 ant-design-x.antgroup.com (官网里的镜像链接也要更新)

#### Next Milestone

- Mobile interactive support
- Assistant/Mobile type component style
- Bundle size reduce

**Comment by wkABXY** [comment]
通义 开发文档能再详细一点么。能给个结合 useXChat 中 onRequest的案例么。please。

**Comment by YumoImer** [comment]
> 通义 开发文档能再详细一点么。能给个结合 useXChat 中 onRequest的案例么。please。

没问题，新提一个issues吧

**Comment by afc163** [comment]
这里还没搞完。

**Comment by YumoImer** [comment]
https://github.com/ant-design/x/pull/262 其中对首页优化了一波，设计 Tab 要整体优化一番，我加个 Todo

**Comment by afc163** [comment]
这里的搞搞完关掉？

**Comment by afc163** [comment]
好像没去发 
<img width="361" alt="图片" src="https://github.com/user-attachments/assets/c0c8cff7-6d6a-430d-b8ad-e8b54e93c9a9" />

**Comment by afc163** [comment]
- [ ] 🚗 国内镜像 ant-design-x.antgroup.com (官网里的镜像链接也要更新)

这个也没改。

**Comment by zombieJ** [comment]
done. closed

**Comment by afc163** [comment]
https://www.echojs.com/news/42710 咋被删了。

**Comment by afc163** [comment]
https://juejin.cn/spost/7449549889165475852 也是 404

**Comment by afc163** [comment]
https://dev.to/afc163/ant-design-x-craft-ai-driven-interfaces-effortlessly-16o9

**Comment by afc163** [comment]
https://www.echojs.com/news/42711
