### ISSUE TITLE
[ Todo List ] Mobile Support

### ISSUE THREAD

**Issue by YumoImer** [ant-design/x#440]
## 全局｜工程

- [ ] 性能优化
    - [ ] 渲染优化
    - [ ] 内存泄漏优化
- [ ] 构建体积优化
- [ ] 全局配置相关
    - [ ] 全局移动开关
- [ ] 全局样式适配
    - [ ] 基础 Token
- [ ] 全局通用交互适配
    - [ ] Mouse 与 Touch

## 通用｜Bubble

- [ ] 支持 sider/actions 扩展位
![image](https://github.com/user-attachments/assets/580bdb41-115e-48f1-81a9-e84822c9c1b2)
- [ ] 支持移动 Touch Bar
![image](https://github.com/user-attachments/assets/a51978bb-0971-4b9c-93d5-a1e72c7a10fc)

## 通用｜Conversations

- [ ] 新增配套 useConversations 协助 Conversations 做数据管理
- [ ] 支持滑动菜单交互
![image](https://github.com/user-attachments/assets/cbe27011-90b6-43df-baa8-bf8e73fbabfc)
- [ ] 支持标题、描述、扩展
![image](https://github.com/user-attachments/assets/fec6d6c9-e6a7-4ab6-9533-e481575fef55)

## 唤醒｜Welcome

- [ ] variant 样式变体
![image](https://github.com/user-attachments/assets/0f4b7ac1-293c-4135-9e74-d6b47984b5c3)

## 唤醒｜Prompts

- [ ] 增加 DEMO 布局变体，图标+标题+描述 横向展示
![image](https://github.com/user-attachments/assets/732b7bdc-adcf-433a-9a62-bc5f6472e1a2)
- [ ] 弹出层交互 Demo
![image](https://github.com/user-attachments/assets/69014e1d-1e50-46f8-94bb-40cd58bdbc2d)

## 表达｜*Attachment

- [x] 暂无

## 表达｜Sender

- [ ] 支持 Sender.Footer 扩展组件，用以支持类似文件上传入口等需求
![image](https://github.com/user-attachments/assets/b319acdc-be1d-49d3-8189-b5dad3b50407)
- [ ] 支持移动语音输入交互
![image](https://github.com/user-attachments/assets/2eebbc5e-e1cc-4c59-ae38-37d70a831956)
- [ ] 组合 Prompts 的 Demo 示例
![image](https://github.com/user-attachments/assets/39730fe8-5d08-40c6-87a7-3e8b921314d3)

## 表达｜Suggestion

- [x] 暂无

## 确认｜ThoughtChain

- [ ] 交互样式变体
![image](https://github.com/user-attachments/assets/3f8489f0-b827-45ac-a3f3-faa0cf063d09)
![image](https://github.com/user-attachments/assets/6188606d-565a-429e-b944-3267361610fe)

### 新增：内容折叠组件

![image](https://github.com/user-attachments/assets/6d22fa72-5903-4608-9db2-5768916ecf7c)

### 新增：ActionsBar

![image](https://github.com/user-attachments/assets/53ca15b8-6ec9-46ab-bd62-ffcdadd1f81a)

### ICON

- [ ] AI 标识

**Comment by iamlhh** [comment]
非常期待。
